# Spring Basic
spring:
  profiles:
    active: dev

# Other
mybatis:
  mapper-locations: classpath:/mapper/*

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem::world_x;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    root: info
    cncsl:
      ft:
        mybatis: DEBUG